// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeKfelfEqRRHuWpLS7E6L0Enep84joIvw',
    appId: '1:366050694634:web:a9c3b0b36e930970760e93',
    messagingSenderId: '366050694634',
    projectId: 'primaadi',
    authDomain: 'primaadi.firebaseapp.com',
    storageBucket: 'primaadi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ99CLBDVpNmcrPeVUEqK5MiEFgHVu8uo',
    appId: '1:366050694634:android:54582e14aa944e78760e93',
    messagingSenderId: '366050694634',
    projectId: 'primaadi',
    storageBucket: 'primaadi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWemkp2LyW7iu3TNouiT3_-LlyZslhi_w',
    appId: '1:366050694634:ios:f2954f3013b25741760e93',
    messagingSenderId: '366050694634',
    projectId: 'primaadi',
    storageBucket: 'primaadi.firebasestorage.app',
    iosBundleId: 'com.prima.aiAssistedDss',
  );

}